name: Deploy to Production

on:
  push:
    branches: [ prod ]
    paths: ['itcc-website-frontend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Production VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/apps/prod/itcc-website-frontend
          
          # Pull du code
          git pull origin prod || git clone https://github.com/ITCloud-Consulting/itcc-website-frontend.git .
          
          # Arrêt du container existant
          docker-compose down || true
          
          # Construction et démarrage
          docker-compose up -d --build
          
          # Nettoyage des images inutilisées
          docker image prune -f