name: Deploy to Production

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # ou '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          # Créer le dossier de production s'il n'existe pas
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "mkdir -p /var/www/prod"

          # Synchroniser les fichiers (exclure node_modules et .git)
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='node_modules' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.env.local' \
            --exclude='.next/cache' \
            ./ $VPS_USER@$VPS_HOST:/var/www/prod/

          # Installer les dépendances de production sur le serveur
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd /var/www/prod && npm ci --legacy-peer-deps --only=production"

          # Redémarrer l'application (PM2)
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd /var/www/prod && pm2 reload itcc-website-frontend || pm2 start npm --name 'itcc-website-frontend' -- start"
